version: '3'
services:
  # ubuntu
  magit:
    build:
      context: .
      dockerfile: Dockerfile
    image: mamewotoko/magit-docker
    network_mode: host
    environment:
      # to fit to terminal size
      - COLUMNS=${COLUMNS}
      - LINES=${LINES}
    volumes:
      - ./:/gitrepo
      # ssh key
      #- ./.ssh:/root/.sssh
      # git config
      #- ./.gitconfig:/root/.gitconfig

  # alpine
  magit-slim:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: mamewotoko/magit-docker:slim
    environment:
      # to fit to terminal size
      - COLUMNS=$COLUMNS
      - LINES=$LINES
    volumes:
      - ./:/gitrepo
      # ssh key
      #- ./.ssh:/root/.sssh
      # git config
      #- ./.gitconfig:/root/.gitconfig
